// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sevfkwdtpwliycfdwwmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldmZrd2R0cHdsaXljZmR3d213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMjQxMjEsImV4cCI6MjA2NjgwMDEyMX0.f-9JFOlBllN9hwvEAfoUIm5CXyNLj6P9oBy93Y22UHo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});